<?php $this->layout('layout::default', ['title' => 'Budżet osobisty | BudgetPlanner']) ?>

<main class="py-4 px-3 m-auto">
  <h1 class="display-4 mb-4 text-center">Budget<wbr>Planner</h1>
  <nav class="budget-menu d-flex justify-content-around flex-wrap">
    <a class="budget-menu_btn btn btn-info" href="#" role="button">Dodaj przychód</a>
    <a class="budget-menu_btn btn btn-info" href="#" role="button">Dodaj wydatek</a>
    <a class="budget-menu_btn btn btn-info" href="#" role="button">Przeglądaj bilans</a>
    <a class="budget-menu_btn btn btn-outline-dark" href="#" role="button">Ustawienia</a>
    <a class="budget-menu_btn btn btn-outline-danger" href="/logout" role="button">Wyloguj się</a>
  </nav>
</main>
