<?php $this->layout('layout::default', ['title' => 'Budżet osobisty']) ?>

<main class="cover py-4 px-3 m-auto">
    <h1 class="display-4 mb-4">Budget<wbr>Planner</h1>
    <p class="lead mb-0">Nigdy więcej znikających pieniędzy.</p>
    <p class="lead mb-4 mb-sm-5">Ogarnij chaos finansów dzięki prostej aplikacji do spisywania swoich zarobków i wydatków.</p>
    <a class="btn btn-primary btn-lg btn-block" href="/login" role="button">Zaloguj się</a>
    <a class="btn btn-outline-secondary btn-lg btn-block" href="register.html" role="button">Zarejestruj się</a>
</main>
